name: .NET Framework 4.8

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Restore the application
      run: msbuild Launcher.cn.csproj /t:Restore /p:Configuration=Release

    - name: Build Solution
      run: msbuild Launcher.cn.csproj /p:Configuration=Release /p:Appx_Bundle_Platforms="x64"

    - uses: actions/upload-artifact@v4
      id: artifact-upload-step
      with:
        name: Launcher
        path: Launcher.exe
