name: .NET Framework 4.8

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.2

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Restore the application
      run: msbuild Launcher.cn.sln /t:Restore /p:Configuration=Release

    - name: Build Solution
      run: msbuild Launcher.cn.sln /p:Configuration=Release /p:Appx_Bundle_Platforms="x64"

    - name: Archive Artifacts
      uses: actions/upload-artifact@v4.3.1
      with:
        name: Launcher
        path: Launcher.exe
